### ISSUE TITLE
Voltron doesn't work with GDB+OpenOCD

### ISSUE THREAD

**Issue by khutchens** [snare/voltron#103]
I'm trying to get voltron working with my setup using the following:

gcc-arm-none-eabi (5.2-2015q4), with gdb-py
OpenOCD (0.10.0-dev-00024-gd28ab08)
GDB is connecting to OpenOCD via a pipe (target remote).

Is voltron expected to work in this scenario, i.e. GDB running locally but connecting to a remote target? I'm getting exceptions on 'target' not being defined. No hardware with me so I can't post the exact error but will as soon as I can.

If it's not currently supported I'd be happy to help make that happen.

**Comment by snare** [comment]
I haven't tried it with OpenOCD but it does work with some other remote targets (e.g. I used to use it with VMware's debug stub a lot before LLDB had support for talking to it). But yeah if you could post the error info when you can that'd be great. I'm actually working on some embedded stuff at the moment so I can try it with OpenOCD this week as well.

**Comment by davidrb** [comment]
I'm having the same issue.  Here's my voltron_main.log

[voltron_main.log.txt](https://github.com/snare/voltron/files/130009/voltron_main.log.txt)

**Comment by davidrb** [comment]
I managed to get it working with #104.

**Comment by snare** [comment]
Nice, thanks man. I've merged that and will hopefully be using it this week myself.

**Comment by davidrb** [comment]
Looks like that fixed everything except stack view and memory view, which for me cause gdb to hang.

**Comment by snare** [comment]
If you only start the stack view *after* the debugger is running and has stopped, does it still hang?

That's a known bug with GDB that came down to “GDB hangs if you x/s some addresses even without Voltron loaded”. I keep meaning to do something about it and I forgot it isn’t in the FAQ or anything.

**Comment by khutchens** [comment]
Hey sorry for the slow response. It looks like davidrb's change did fix the original issue for me as well. I'm running into some other bugs but I'm going to close this issue and will open new ones if I can't resolve things on my own.
