### ISSUE TITLE
No  .log files at ~/.voltron

### ISSUE THREAD

**Issue by dianapinkberry** [snare/voltron#107]
I've enabled `debug_logging` in my config(`default.cfg`), but in `~/.voltron/ ` wasn't created `voltron_debugger.log` and `voltron_main.log` files :(
All's  working with LLDB. This problem is just with GDB. Mac OS X 10.11.3

**Comment by snare** [comment]
Please enable debug logging per the README file in ~/.voltron/config rather than in the default.cfg.
