### ISSUE TITLE
'Server' object has no attribute 'client_summary'

### ISSUE THREAD

**Issue by williballenthin** [snare/voltron#110]
Exception while running `status`.
```
(gdb) voltron status
Python Exception <class 'AttributeError'> 'Server' object has no attribute 'client_summary': 
Error occurred in Python command: 'Server' object has no attribute 'client_summary'
```

Looking at voltron.core, it seems that `Server` don't have this attribute. Maybe it was accidentally removed at some point?

Here's the offending line:
https://github.com/snare/voltron/blob/master/voltron/entry.py#L75

**Comment by snare** [comment]
Ah yep I think that was removed. `voltron status` doesn't really mean much anymore since clients don't register for notifications anymore, they just do blocking requests. I'll look at either adding support for this command again or just removing the command.

**Comment by snare** [comment]
Removed in 7cc41a2889278546489a2a587a56f4340454a8e8
