### ISSUE TITLE
Symbol not found: __PyCodecInfo_GetIncrementalDecoder

### ISSUE THREAD

**Issue by CallumHoward** [snare/voltron#111]
I get the following output after loading lldb
```
Exception <type 'exceptions.ImportError'> raised while loading Voltron: dlopen(/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
```
Running voltron init gives
```
error: 'voltron' is not a valid command.
error: Unrecognized command 'voltron'.
```
Using latest version pulled with commit hash: 763a246f78e7a3a2501a8595f9f6ca94e24bb800
lldb --version gives: lldb-340.4.119.1

**Comment by snare** [comment]
I encountered this issue myself but haven't gotten around to finding a proper fix yet. The problem occurs only when using Python installed with Homebrew, rather than the system's Python. I'll investigate.

**Comment by snare** [comment]
If you uninstall Homebrew's Python it should work fine, but that's not a very good solution.

**Comment by snare** [comment]
After re-installing Python with Homebrew I can't reproduce this issue any more. Maybe try the suggestions in this SO article:

http://stackoverflow.com/questions/34386527/symbol-not-found-pycodecinfo-getincrementaldecoder-trying-to-register-a-packa

**Comment by OkanEsen** [comment]
Reinstalling Python with Homebrew doesn't work for me unfortunately, it throws the same error for me.

```
Exception <type 'exceptions.ImportError'> raised while loading Voltron: dlopen(/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
(lldb) command source -s 1 '/Users/Okan/./.lldbinit'
Exception <type 'exceptions.ImportError'> raised while loading Voltron: dlopen(/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
(lldb) exit
```

**Comment by richo** [comment]
I'm pinned to Python 2.7.9 from homebrew for this reason. 2.7.10 broke it.
I haven't worked out why, but it does solve the issue

**Comment by snare** [comment]
OK, so the problem seems to be that LLDB is linked with the system Python and when homebrew Python's installed the brew core libs get stuck in the `sys.path` and then fail to load. This might not be the best solution, but it seems to work:

1) Put [this file](https://gist.github.com/snare/88bca2a34f00dc6b0fe17679c5082529) somewhere
2) Before you source Voltron in your `.lldbinit`, source the script:

    command script import /path/to/fix_brew_python.py
    command script import /path/to/voltron/entry.py

Let me know if this works for everyone and I'll see if there's a clean way to integrate it into Voltron.

**Comment by snare** [comment]
I integrated it into `entry.py` and it works for me with and without Homebrew Python now. Give [this branch](https://github.com/snare/voltron/tree/bugfix/brew_broken_python) a go.

**Comment by OkanEsen** [comment]
Works great now, thank you very much!

**Comment by snare** [comment]
Great, thanks :)

**Comment by richo** [comment]
Fix looks good, but I'm still at a loss for why it works on brewed 2.7.9?
