### ISSUE TITLE
Stack View Alignment

### ISSUE THREAD

**Issue by theqlabs** [snare/voltron#122]
for whatever reason my stack view doesn't seem to be based off of `stack pointer` so i'm missing a chunk from the stack when the view loads. see attached. 

![screen shot 2016-04-07 at 11 33 45 pm](https://cloud.githubusercontent.com/assets/823183/14375846/5cfca83c-fd19-11e5-9fe1-9f0bfa10bbb3.png)

in the photo, the stack view should display `00007FFF84735E40` and up, right? anyway to make this happen?

**Comment by snare** [comment]
Huh, yeah. I'll take a look now.

**Comment by snare** [comment]
Just FYI in the mean time, you can replicate the functionality of the stack view with the memory view like this:

`$ voltron v m --reg rsp -d`

It's just flipped with the SP at the top.

**Comment by snare** [comment]
Fixed in 69d86d8ca65719f51a9049884126a691cea41f7d

Sorry, that was dumb.

**Comment by theqlabs** [comment]
sweet, will grab and test tmw. thanks man!
