### ISSUE TITLE
Can voltron be used with an emulator?

### ISSUE THREAD

**Issue by arcanis** [snare/voltron#125]
That may be a bit farfetched, but when working with emulators, I've often been repelled by the sad state of the usual debugging tools. When these tools exist, they're often provided along with the emulators themselves, and don't really provide good debugging experiences (which makes sense, since the emulators authors prefer to spend more time on the emulator rather than on the debugging interface).

When working on Virtjs, I worked a bit on an Curses interface that would load an emulator, and talk to it via a designated API (for example, my emulators exposed a `readUint8` function that allowed the debugger to fetch a value from any place inside the emulated memory). It worked quite fine.

When seeing your project, I can't help but wonder if some kind of adapter would work, allowing to debug emulated programs instead of native ones. I'm not sure how would Voltron be able to communicate with the emulator process (maybe via some kind of HTTP api, since that's something that most programming languages natively support?), but that would be really interesting.

**Comment by snare** [comment]
I think Voltron could be useful in providing the glue to improve the kind of tools you describe. Voltron is designed primarily for debuggers with a Python interface, but I'm sure an adaptor could be rigged up for something without.

You'd need to implement a debugger plugin with the `DebuggerAdaptor` and `DebuggerCommand` classes. See the [LLDB plugin](https://github.com/snare/voltron/blob/master/voltron/plugins/debugger/dbg_lldb.py) for an example. If the debugger does not have a Python API, so Voltron can't be loaded into it, the Voltron server would need to be run in another process, and the `DebuggerAdaptor` subclass would communicate with the emulator debugger via whatever other method was suitable.

Additionally, any architecture-specific stuff that happens in the views would need to be implemented. Register names and layouts would need to be added to the register view, etc. If you have a specific use case you're interested in I can have a look at the debugging tools and see what would be involved in implementing it.
