### ISSUE TITLE
error: Could not find suitable distribution for Requirement.parse('scruffington>=0.3.2')

### ISSUE THREAD

**Issue by fabubaker** [snare/voltron#137]
Voltron gives the above dependency error when attempting to install on Ubuntu 15.10. 

I've install scruffington 0.3.2 using `pip install scruffington`. But I still get this error:

![screenshot from 2016-04-14 16-39-35](https://cloud.githubusercontent.com/assets/9405286/14529965/85d822ea-025f-11e6-9ffc-3e68012bb24b.png)

I've done everything mentioned here as well: [Voltron on Ubuntu with GDB](https://github.com/snare/voltron/wiki/Voltron-on-Ubuntu-with-GDB)

**Comment by ahjkk** [comment]
you need type

sudo pip install scruffington

**Comment by fabubaker** [comment]
Yep, I did it with `sudo` the first time around, still giving me this error.

**Comment by snare** [comment]
You'll probably need to `pip3 install scruffington`

**Comment by fabubaker** [comment]
That did it! Voltron is awesome!

**Comment by snare** [comment]
Nice!
