### ISSUE TITLE
Exception after Voltron loaded in lldb 

### ISSUE THREAD

**Issue by asetsuna** [snare/voltron#138]
```
Voltron loaded.
(lldb) target create "regex"
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 498, in serve_forever
    display_hostname = self.host != '*' and self.host or 'localhost'
AttributeError: 'ThreadedUnixWSGIServer' object has no attribute 'host'

Current executable set to 'regex' (x86_64).
```
OS X 10.11

**Comment by asetsuna** [comment]
Voltron works

**Comment by snare** [comment]
Which version of LLDB are you running?

Can you try cb43eac6879e29fe5a4c0261800263d4899cbfee

**Comment by asetsuna** [comment]
**lldb-350.0.21.3 **

I cloned  [cb43eac](https://github.com/snare/voltron/commit/cb43eac6879e29fe5a4c0261800263d4899cbfee) and tested. The exception remains.

**Comment by snare** [comment]
I can't reproduce the problem here with the same version. Could you please run a session with the test inferior included with Voltron as described [here](https://github.com/snare/voltron/wiki/Troubleshooting) and see if it still happens?

**Comment by snare** [comment]
Also, try 950a2f3202aa9041a9d29cf2009696fdc88283ae.

A workaround might be to disable the domain socket listener in your config. To try this, put the following in your `~/.voltron/config`:

```
server:
    listen:
        domain: false
```

**Comment by asetsuna** [comment]
OK, [950a2f3](https://github.com/snare/voltron/commit/950a2f3202aa9041a9d29cf2009696fdc88283ae)  fixed the problem, no exception now.  I tried both the config set or not . 

Thank you, :).

**Comment by snare** [comment]
Awesome, thanks!
