### ISSUE TITLE
easy_install is failing to download scruffington

### ISSUE THREAD

**Issue by OranShuster** [snare/voltron#142]
using python3 setup.pt install (because of the ubuntu python bug thing)
you get the following messages while installing

Reading https://pypi.python.org/simple/scruffington/
No local packages or download links found for scruffington>=0.3.2

going to that link manually shows these packages
scruffington-0.3.3-py2.py3-none-any.whl
scruffington-0.3.1.tar.gz
scruffington-0.3.2-py2.py3-none-any.whl

so somehow PIP/easy_install doesn't understand that the version exists.
i edited the setup.py file to not have the 0.3.2 version requirement and it downloaded 0.3.1 automatically

**Comment by snare** [comment]
Thanks, I'll see if I can reproduce it here and find a better solution than requiring `pip install`.

**Comment by snare** [comment]
Actually, I pushed an `sdist` for scruffy so that should solve that problem. I think if you're using a more modern version of `pip`/`setuptools` with `wheel` support it's fine, but if you're using an older version without it won't work.

**Comment by OranShuster** [comment]
even through this was a "fresh" install of python, setuptools still had to be updated manually for wheel support. i guess this is a non-issue
