### ISSUE TITLE
invalid literal for int() with base 10 when using memory viewer -a

### ISSUE THREAD

**Issue by OranShuster** [snare/voltron#143]
using the following command
voltron view memory -a 0x0804a07c yields the error in the subject
i tried any kind of format, such as-
0x0804a07c
0804a07c 
"0x0804a07c"
"0804a07c"

now, my python is "meh" at best so the only i understand is that you have a format string that you are using to parse the memory address. other then the address should be in hex i'm getting nothing

**Comment by snare** [comment]
Derp. Fixed in 3ced980707fec29530ea5969e373b5353894b9ba.

**Comment by snare** [comment]
Any of the formats you tried should work now.
