### ISSUE TITLE
Voltron views fails with dbg_gdb.py error

### ISSUE THREAD

**Issue by dgbuser** [snare/voltron#147]
- OS X 10.10.5 w/Python 2.7.11 via Macports/Python 2.7.10 via Apple

- Voltron installed via dist(Macports)/pip/source(github) to both System Python as well as Macports.

- LLDB requires uses of either System Python or at least symlink the _io.so from System Python to Macports Python dir (after renaming _io.so to _io.so.bak in Macports) 

No matter which debugger Voltron is launched with (LLDB/GDB/VDB), all produce the following error. VDB offers the error immediately after running the script command while, LLDB & GDB offer "Voltron loaded" when loaded via init file but, produce the error upon requesting any views:

An error occurred while loading Voltron:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1.4-py2.7.egg/voltron/entry.py", line 57, in <module>
    import voltron
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1.4-py2.7.egg/voltron/__init__.py", line 95, in <module>
    setup_env()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1.4-py2.7.egg/voltron/__init__.py", line 31, in setup_env
    pkg_plugins=PluginDirectory('plugins', parent=PackageDirectory())
  File "build/bdist.macosx-10.10-x86_64/egg/scruffy/env.py", line 40, in __init__
    self.add(**kwargs)
  File "build/bdist.macosx-10.10-x86_64/egg/scruffy/env.py", line 105, in add
    self._children[key].prepare()
  File "build/bdist.macosx-10.10-x86_64/egg/scruffy/file.py", line 431, in prepare
    self.load()
  File "build/bdist.macosx-10.10-x86_64/egg/scruffy/file.py", line 437, in load
    self._pm.load_plugins(self.path)
  File "build/bdist.macosx-10.10-x86_64/egg/scruffy/plugin.py", line 59, in load_plugins
    self.load_plugins(filepath)
  File "build/bdist.macosx-10.10-x86_64/egg/scruffy/plugin.py", line 55, in load_plugins
    mod = imp.load_module(modname, file, path, descr)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1.4-py2.7.egg/voltron/plugins/debugger/dbg_gdb.py", line 607, in <module>
    class GDBCommand(DebuggerCommand, gdb.Command):
AttributeError: 'module' object has no attribute 'Command'

**Comment by snare** [comment]
I haven't tried it with Python installed from MacPorts, only Homebrew.

What does `python -m voltron view` yield?

Or `/usr/bin/python -m voltron view`

**Comment by snare** [comment]
From that traceback it looks like the "am I running inside GDB" check is passing when loading the GDB plugin, then it's failing trying to load something from the GDB module.

What does `python -c "import gdb;print(gdb.__file__)"` show?

**Comment by dgbuser** [comment]
$ python -m voltron view
usage: __main__.py view [-h]

                        {register,backtrace,back,breakpoints,memory,reg,mem,disasm,break,bp,stack,bt,c,b,d,cmd,m,st,s,r,command,t,dis}
                        ...
__main__.py view: error: too few arguments

$ /usr/local/bin/python -m voltron view
usage: __main__.py view [-h]

                        {register,backtrace,back,breakpoints,memory,reg,mem,disasm,break,bp,stack,bt,c,b,d,cmd,m,st,s,r,command,t,dis}
                        ...
__main__.py view: error: too few arguments

$ python -c "import gdb;print(gdb.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named gdb

Additionally ...
gdb$ python print("Hello World")
Hello World

gdb$ python print sys.version
2.7.11 (default, Mar 18 2016, 23:24:42)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

**Comment by snare** [comment]
Does `python -m voltron view reg` work or does it throw the same error as `voltron view reg`?

**Comment by snare** [comment]
If it does you can use that to run the views. I'll try to reproduce your issue here.

**Comment by dgbuser** [comment]
$ python -m voltron view reg
Error: HTTPConnectionPool(host='localhost', port=5555): Max retries exceeded with url: /api/request (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPCon>

(when piped to 'less')
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/voltron-0.1.4-py2.7.egg/voltron/view.py", line 257, in run
    msg = e.message.args[1].strerror
IndexError: tuple index out of range

**Comment by snare** [comment]
Ah, that error is somewhat deceptive. The `IndexError` needs to be fixed, but the `HTTPConnectionPool` error just indicates that it can't connect to the backend. The view looks like it's working. If you run GDB, load an inferior set a breakpoint and run it until it hits the breakpoint, the view should update.

**Comment by dgbuser** [comment]
With Macports python, tmuxinator is happy with "python -m voltron view _____" than "voltron view _____". Yes, now I understand error message better. Voltron looks to be working as expected for both LLDB & GDB. VDB is still provides the same error but, not the best OS X support anway. Thanks you much for your help!

**Comment by snare** [comment]
Excellent! VDB isn't really supported on OS X, I've only tried it on Windows. I'll give it a run some time and see if it's easy to fix.

**Comment by nongiach** [comment]
I have the same issue, the problem occurs when we can "import gdb" even when not in an instance of gdb.
A fix could be something like that (not sure that's the best way but it should work):
set a vars in voltron/entry.py which is sourced from gdb.
And check if it is set in voltron/plugins/debugger/dbg_gdb.py.
Thx for this nice work on Voltron.

**Comment by snare** [comment]
Please try the latest version from GitHub with the install script

**Comment by snare** [comment]
Also please open a new issue if necessary
