### ISSUE TITLE
viewing register causes GDB hanging

### ISSUE THREAD

**Issue by lazywei** [snare/voltron#151]
Hi,

I noticed that if I run
```
voltron view reg
```
in another terminal, then my gdb will hang like this

```
(gdb) finish
Run till exit from #0  0x0000000000401a43 in Gets (dest=dest@entry=0x5561dc78 "\020\203\006") at support.c:163
getbuf () at buf.c:16
16	buf.c: No such file or directory.
1: x/i $pc
=> 0x4017b4 <getbuf+12>:	mov    $0x1,%eax
Value returned is $6 = 0x5561dc78 "012"
(cursor hangs here)
```

If I quit the register view, everything works fine.

**Comment by snare** [comment]
What platform and version of GDB are you on?

Could you please follow the steps [here](https://github.com/snare/voltron/wiki/Troubleshooting) and post your debug logs?

Thanks

**Comment by lazywei** [comment]
Platform:
```
$ uname -a
Linux cl1 3.13.0-71-generic #114-Ubuntu SMP Tue Dec 1 02:34:22 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

GDB:
```
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
```

And the logs (main.log and debugger.log):
https://gist.github.com/lazywei/48dfc51ff0f6397f48da8f1355fd372e

**Comment by snare** [comment]
Is that Ubuntu 14.04?

**Comment by lazywei** [comment]
yes, i think so

**Comment by snare** [comment]
Oh wait it's there in the GDB version. Cool.

**Comment by snare** [comment]
So, when you ran through those steps I guess GDB hung after `run` and you weren't able to `stepi`?

**Comment by lazywei** [comment]
GDB hung after `finish` and I wasn't able to `stepi`

**Comment by snare** [comment]
I can't reproduce this issue.  I've set a breakpoint in the test inferior, hit it and `finish`ed successfully without GDB hanging.

Can you please follow the steps in the Troubleshooting page I linked exactly (using the test inferior included with Voltron, and without `finish`) and make sure that also works as expected?

If you could try to reproduce the issue with an inferior that I have access to that would be helpful in trying to reproduce the issue here.

**Comment by lazywei** [comment]
I guess this case is related to the executable I'm debugging with. So I'm not sure if this is really a bug for Voltron. :-P

**Comment by snare** [comment]
Did you try it without loading Voltron? GDB can be pretty crashy at the best of times :(

**Comment by lazywei** [comment]
It works fine with Voltron --- as long as I don't open register view. lol
I won't mind if you prefer to close this issue, btw.

snare <notifications@github.com> 於 2016年6月13日 週一 下午11:59寫道：

> Did you try it without loading Voltron? GDB can be pretty crashy at the
> best of times :(
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/snare/voltron/issues/151#issuecomment-225626001>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ACtX-_7sqSC-f6xjAIxmxwvlRzokwOdgks5qLX59gaJpZM4IujGU>
> .
>
-- 
Chih-Wei (Bert)

**Comment by snare** [comment]
No worries. Thanks.
