### ISSUE TITLE
ImportError: No module named blessed

### ISSUE THREAD

**Issue by AndersenTobias** [snare/voltron#154]
Hi, I'm getting this error:

```
$ lldb a.out 
An error occurred while loading Voltron:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/voltron/entry.py", line 43, in <module>
    import blessed
ImportError: No module named blessed

(lldb) target create "a.out"
Current executable set to 'a.out' (x86_64).
(lldb)
```

I'm using a Homebrew:ed version of Python 3.5. I find it weird -- `blessed` is installed and should be on the `sys.path`...?

**Comment by snare** [comment]
LLDB will be linked against the system Python, rather than the Homebrew Python, so that's where it will be looking for packages. It's easiest currently just to install Voltron into the system Python's site-packages (or with --user if you like).

I've been meaning to support a better way to do this using a virtualenv, but I haven't done it yet.

**Comment by theqlabs** [comment]
Hey so, what is the solution here? Getting this same error using GDB 7.11.1 on Ubuntu 16.04.1 (LTS)

```
An error occurred while loading Voltron:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/voltron-0.1.5-py2.7.egg/voltron/entry.py", line 43, in <module>
    import blessed
ImportError: No module named 'blessed'
```

Should voltron be installed in all dist/site-packages for all Python versions?

**Comment by snare** [comment]
Just whichever version of Python GDB is linked against

**Comment by theqlabs** [comment]
I guess my actual question is how do I specify the python version to Voltron upon installation?

**Comment by snare** [comment]
I wrote [some more doco](https://github.com/snare/voltron/wiki/Installation) on installing Voltron on systems with multiple Python versions if you guys would like to take a look

**Comment by theqlabs** [comment]
Perfect man. Thanks for that. Worked well for me.
