### ISSUE TITLE
Feature: Resolve pointers in registers

### ISSUE THREAD

**Issue by Grazfather** [snare/voltron#160]
Just like PEDA does.
![x](https://cloud.githubusercontent.com/assets/497310/18057837/757f01ac-6dc6-11e6-9969-5e3be1291044.png)

**Comment by snare** [comment]
`voltron v r -i`

**Comment by snare** [comment]
![image](https://cloud.githubusercontent.com/assets/504561/18057910/4073ca62-6e55-11e6-9228-5ab975276c7d.png)

**Comment by Grazfather** [comment]
😍
