### ISSUE TITLE
dependency issues

### ISSUE THREAD

**Issue by lucasduffey** [snare/voltron#172]
# install time
./install.sh will fail if you don't have python3-pip. Might want to install that as part of the script.

# run time (import voltron)
* you need: blessed, flask, scruffy.plugin, maybe more... I stopped before installing scruffy.

**Comment by snare** [comment]
The install script should install those Python deps. Added `python3-pip`/`python-pip` on Linux in 7c9b13495bd316d2c768ef110e4bca13d2c72ae3.

**Comment by snare** [comment]
Well, `pip` should install those deps for you.
