### ISSUE TITLE
If using gdb as debugger, how to get the same source view like lldb

### ISSUE THREAD

**Issue by YanShenChun** [snare/voltron#173]
Hi, snare

Thanks for your great share and voltron is really awesome. I just saw the below `source` view when using lldb with voltron:

**voltron v c --lexer c "source list -a \$rip -c 25"**

But I am working on the gdb debugger and I just found the `list` command but which can't make the same effect like lldb. Also I don't want to use the tui mode in gdb.

Do you have any idea about this? I know this may not be a matter with voltron. But if we can't find the same command in gdb, can voltron help us to do that??

Any help is highly appreciated.

**Comment by snare** [comment]
Hey, I couldn't see an easy way to do this with just GDB commands (there might be but I gave up). Here is a quick view I knocked up that does the job though:

```
"""
Quick view to show source code in GDB with an arrow pointing to the current
line. This kinda sucks but it was knocked up quickly without adding any
back-end API code, just using commands.
"""

from voltron.view import *
from voltron.plugin import *
from voltron.api import *
from voltron.lexers import *
import pygments
import pygments.formatters
import re


class GDBSourceView(TerminalView):
    @classmethod
    def configure_subparser(cls, subparsers):
        sp = subparsers.add_parser('source', help='list the source code')
        VoltronView.add_generic_arguments(sp)
        sp.add_argument('--lexer', '-l', action='store',
                        help='apply a Pygments lexer to the source output (e.g. "c")',
                        default=None)
        sp.set_defaults(func=GDBSourceView)

    def build_requests(self):
        return [
            api_request('command', command='list *$pc', block=self.block),
            api_request('command', command='frame', block=self.block)
        ]

    def render(self, results):
        [l_res, f_res] = results

        # Set up header & error message if applicable
        self.title = '[source]'

        # don't render if it timed out, probably haven't stepped the debugger again
        if l_res.timed_out:
            return

        if l_res and l_res.is_success:
            # Get the source output
            source = l_res.output

            # Find the line we're on and stick an arrow there
            try:
                m = re.search('\(.*:(\d+)\)', f_res.output.split('\n')[1])
                line_num = m.group(1)
                lines = []
                for line in source.split('\n'):
                    if re.match('^' + line_num + '\s', line):
                        lines.append(' -> ' + line)
                    else:
                        lines.append('    ' + line)
                source = '\n'.join(lines)
            except:
                pass

            # Highlight output
            try:
                if self.args.lexer:
                    lexer = get_lexer_by_name(self.args.lexer)
                    source = pygments.highlight(source, lexer, pygments.formatters.get_formatter_by_name(
                                                self.config.format.pygments_formatter,
                                                style=self.config.format.pygments_style))
            except Exception as e:
                log.warning('Failed to highlight source: ' + str(e))

            # Build output
            self.body = source.rstrip()
        else:
            log.error("Error getting source: {}".format(res.message))
            self.body = self.colour(res.message, 'red')

        # Call parent's render method
        super(GDBSourceView, self).render(results)


class GDBSourceViewPlugin(ViewPlugin):
    plugin_type = 'view'
    name = 'source'
    view_class = GDBSourceView
```

Put this in `~/.voltron/plugins/source.py` and you should be able to do:

    $ voltron v source --lexer c

And get something like this:

![image](https://cloud.githubusercontent.com/assets/504561/18697709/25651b90-8007-11e6-8901-26807c10585a.png)

**Comment by snare** [comment]
I might eventually add a proper source view that works across all the debugger backends, but I'll need to add some back end plumbing to do it properly.

**Comment by YanShenChun** [comment]
Hi, snare

Very sorry for my late response. :( . your reply is so timely.
I have tried your code. And the code is working well other than missing the debugger sign (**->**)

![no_debugger_sign](https://cloud.githubusercontent.com/assets/4585140/18780148/c0cd9fdc-81ae-11e6-8bbb-e73e9cbec41b.png)

Would you like to help on this?

**Comment by snare** [comment]
Replace that `pass` with a `raise` and let me know what the exception says.

**Comment by snare** [comment]
Also maybe stick a `print(f_res.output)` in there. That code is not very robust, just super quick, so it doesn't really handle anything but the output I got from the `frame` command.

**Comment by YanShenChun** [comment]
Hi, snare

You are right and the root cause is just the code position you pointed to me.

f_res.output on my box is:
`#0  main () at test.cc:6 `
`6    std::string str = "hello,world";`

so I just update 
**`m = re.search('\(.*:(\d+)\)', f_res.output.split('\n')[1])`**  

as

 **_`m = re.search('.*:(\d+)', f_res.output.split('\n')[0])`_**

Now it is working well.

Thanks so much for your help!!

**Comment by snare** [comment]
Excellent

**Comment by FallenWarrior2k** [comment]
Sorry for necro-ing an old thread, but I just found this and after experimenting around a bit, I wanted to point out for other people that might find this that `list *$rip` works in GDB to achieve a similar effect as `source list -a $rip` for LLDB. Sadly, however, it doesn't explicitly mark the current line, but it does work out of the box.
