### ISSUE TITLE
apt-get shouldn't be inclued in install.sh

### ISSUE THREAD

**Issue by c02y** [snare/voltron#180]
You should not use platform specific commands such as `apt-get` or `dnf` or `yum` in install.sh file but does not mention it.

Maybe the requirements should be put inside the README file, actually, I comment the line "install_apt" out, the install.sh file works fine, `voltron` will be installed (I already installed the requirements such as llibreadline6-dev, Fedora has another name).

**Comment by snare** [comment]
You can skip the `apt-get` with the `-s` flag. I'll add some better distro detection, but the `apt-get` is staying.

**Comment by snare** [comment]
Also see the [Installation documentation](https://github.com/snare/voltron/wiki/Installation#linux). I'll add a note about which distros are supported in the README.
