### ISSUE TITLE
Update six in install.sh on macOS

### ISSUE THREAD

**Issue by snare** [snare/voltron#183]

**Comment by ivan-krukov** [comment]
It might be necessary to install `six` from source.

The default `pip-2.7 install` will try install into `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras`, which is not writable.
Instead, a newer version of `six` can be installed into `/Library/Python/2.7/site-packages/` by using `python2.7 setup.py install` from source.

Reso: http://stackoverflow.com/a/37026323/1414230

**Comment by mmontag** [comment]
You can also add the `--ignore-installed six` option to the `pip install` statements. Worked for me.

**Comment by mmontag** [comment]
...well, not quite that simple, I also had to create this file /Library/Python/2.7/site-packages/elcap.pth:

`import sys; sys.path = ['/Library/Python/2.7/site-packages'] + sys.path`

see http://apple.stackexchange.com/a/210021/34747

Bad situation for macOS.

**Comment by snare** [comment]
You can install it to the user's `site-packages`

`$ pip install six --user --upgrade --ignore-installed` should do it

**Comment by snare** [comment]
Fixed in f640512319570ba3727e81b0d97d07de9a079e67
