### ISSUE TITLE
install.sh fails while trying to install python packages for lldb

### ISSUE THREAD

**Issue by rohshall** [snare/voltron#193]
`
++ tail -1
+ LLDB_SITE_PACKAGES=/usr/lib/python2.7/site-packages
+ install_packages
+ install_apt
+ '[' -n '' ']'
+ install_yum
+ local CMD=
+ '[' -n '' ']'
+ '[' -n '' ']'
+ '[' '' '!=' '' ']'
+ '[' /usr/lib/python2.7/site-packages == /usr/lib/python3.6/site-packages ']'
+ sudo /usr/bin/python2.72.7 -m pip install -U .
sudo: /usr/bin/python2.72.7: command not found
`

My system information:

`
salil@lenovo:~/voltron$ python
Python 3.6.0 (default, Jan 16 2017, 12:12:55) 
[GCC 6.3.1 20170109] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

salil@lenovo:~/voltron$ python2
Python 2.7.13 (default, Dec 21 2016, 07:16:46) 
[GCC 6.2.1 20160830] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 

salil@lenovo:~/voltron$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"

salil@lenovo:~/voltron$ lldb -v
lldb version 3.9.1 ( revision )

salil@lenovo:~/voltron$ gdb -v
GNU gdb (GDB) 7.12.1

`

**Comment by snare** [comment]
Thanks!
