### ISSUE TITLE
No voltron Command

### ISSUE THREAD

**Issue by JeckyOH** [snare/voltron#196]
After I installed the voltron following the instruction and start an instance of lldb,
when I use "voltron view register" to open some views in other iTerm panes, it shows "voltron command not found".
so I add "alias voltron="python -m voltron" to .bash_profile. Then it works.
I want to know is there someone else need to do such things? If so, whether it is better to make such process into install.sh?

**Comment by snare** [comment]
You shouldn't need to do that, the setup.py (run by install.sh) creates the voltron entry point command. 

Did you install with install.sh? What platform?

**Comment by JeckyOH** [comment]
Yeah, I use install.sh on Mac 10.12.3 and I use Python 2.7.

**Comment by Tehada** [comment]
Your executable of voltron shoulb be in `~/.local/bin` Just copy it to your `/usr/local/bin` directory or edit `PATH` to find in this location!

**Comment by aparesse** [comment]
I get the same problems. I run($ install.sh -b lldb) straightly. 

......
$ command script import /path/to/entry.py
it shows me: permission denied

**Comment by nateozem** [comment]
@aparesse 
I think your problem is a different than @JeckyOH, where this person has an issue of **not found**.  The problem relies on the system not finding `voltron` executable file from it's path (that would the value set for `PATH`).  
With yours, you may need to `sudo` when entering lldb: `$ sudo lldb`

**Comment by nateozem** [comment]
@JeckyOH 
If you didn't use `sudo` mode, the binary should be installed along the local user path.
So if you execute this

    $ python -m site --user-site

You may see for an example of

    /Users/<username>/Library/Python/2.7/lib/python/site-packages

If this is the case, then `voltron` should be installed in the `bin` directory, which should be the sibling of `lib` directory. The full path would look like so

    /Users/<username>/Library/Python/2.7/bin/voltron

So be sure and check `PATH` and see if it has `/Users/<username>/Library/Python/2.7/bin` for one of it's paths.

    $ echo $PATH

> If so, whether it is better to make such process into install.sh?

I believe we can't modify any of the user's shell configuration files. So the best option is to inform user (if they need to), to add new path to their system's `PATH`.

Open to opinions and suggestions.

**Comment by snare** [comment]
Ah looks like I forgot that `~/Library/Python/2.7/bin` isn't in the user's path by default because it's been in my `.zshrc` for so many years.

Yeah I think the best option is probably to add a note to the output from the install script that you need to make sure `~/Library/Python/2.7/bin` is in your `$PATH`.

**Comment by aparesse** [comment]
@snare your answer is right, I get it ,thx!

**Comment by aparesse** [comment]
@nateozem the reason that I didn't export the /path/to/python/bin , thanks

**Comment by SethArchambault** [comment]
This issue occurred for me to - glad this post was here! Would be great if it was added it to the readme..

**Comment by nateozem** [comment]
#200
