### ISSUE TITLE
About panes layout

### ISSUE THREAD

**Issue by espressocoder** [snare/voltron#199]
https://camo.githubusercontent.com/f364ec6565b14e266e33005c9cb80e5c7f7b367d/687474703a2f2f692e696d6775722e636f6d2f396e756b7a74412e706e67

can you provide this layout code? thanks

**Comment by snare** [comment]
It's just iTerm panes with the following commands:

    $ voltron v d
    $ voltron v r -i # the -i should be default now so it may be just `voltron v r`
    $ lldb inferior
    $ voltron v s

iTerm panes set up manually or saved to a window arrangement (I normally just set them up kinda like that when I need to use it).

**Comment by aparesse** [comment]
@snare  I mean to layout these panes with tmuxinator

**Comment by snare** [comment]
https://github.com/snare/voltron/wiki/Layout-automation
