### ISSUE TITLE
LLDB Watchpoints Window

### ISSUE THREAD

**Issue by sterling0x1** [snare/voltron#205]
Hi Snare!
Would you be able to add an extra window that displays watchoints in lldb?
Many Thanks!

**Comment by snare** [comment]
Hey, you can use a command view like this:

    $ voltron view command "watch list"

**Comment by sterling0x1** [comment]
I see, that should work fine apparently, thanks for the heads up.

I do have couple more questions, I ask them here I read of making new issue.

1. I installed voltron a few times already with no issues. However latest install is a bit weird, voltron wouldn't load in lldb unless I start lldb as sudo. I never experienced this, in normal terminal voltron view xxx doesn't require sudo. Is there a way I completely uninstall and reinstall it?

2. I saw you've added scrolling feature to memory view. Is there a way to do the same in disasm view?
The reason is, I mainly remote debug ios games, and when it breaks on a watchpoint, most the times the instructions I need are a few lines above the one that it breaks on.
