### ISSUE TITLE
Scrolling in disasm view

### ISSUE THREAD

**Issue by sterling0x1** [snare/voltron#206]
I noticed the scrolling feature in memory view. Is there a way to do the same in disasm view?

**Comment by snare** [comment]
Not currently :( I began to rewrite the view rendering entirely to facilitate this but I don't have time to actively develop it at the moment

**Comment by sterling0x1** [comment]
Fair enough, it's still badass as is. I'll probably buy binary ninja in the near future, I'd love to try Binjatron :)
