### ISSUE TITLE
Can Voltron view Show the Objective-c object infomation

### ISSUE THREAD

**Issue by bucengyongyou** [snare/voltron#210]
im debug a ios app using lldb
when i open a register or stakc view  it seemed like this

X0  000000013FD5BDE0 | ...?.... | => "
                                      "
X1  00000001000BDD5C | ........ | => "btnPressed:"
X2  000000013FD626A0 | .&.?.... | => "]"
X3  000000013FE36740 | @g.?.... |
X4  000000013FE36740 | @g.?.... |

the x0,x1  is a objective-c object  but the register view cant explain it

could you tell me how to configuation to show the objective-c object  thanks

**Comment by snare** [comment]
Voltron doesn't support inspection of objective C objects in the stack view. You'll have to do this manually with LLDB commands.
