### ISSUE TITLE
update voltron views on specific breakpoint without stoping

### ISSUE THREAD

**Issue by DaniloNC** [snare/voltron#211]
I tried to update the voltron panels everytime the program hit thw breakpoint 0x402276 but without stopping the execution using the follow gdb script:

script.txt
```
break *0x402276

commands
silent
continue
end

continue
```

However voltron still showing the message `Target busy`.
Is there a command that a can use to automatic update the voltron views without pausing the execution?
Is there a better way to accomplish this?

**Comment by sunqingyao** [comment]
Same, I'm using LLDB on macOS.

**Comment by snare** [comment]
If you add a `voltron update` to your script that should do the trick
