### ISSUE TITLE
Connection retries: consider using exponential backoff

### ISSUE THREAD

**Issue by merlinND** [snare/voltron#218]
At the following location, it seems that requests are attempted again every second in case they fail:

https://github.com/snare/voltron/blob/e155681615a05fc3949c601a3cb957d8236a11d0/voltron/core.py#L564-L567

In the case the debugger isn't running, e.g. in-between debugging sessions, this causes useless processing and error messages.
Would you consider adding a simple [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) strategy for the retries?

**Comment by snare** [comment]
That would mean it'd take a long time to reconnect when the debugger became available again. Usually I want it to reconnect immediately.

**Comment by merlinND** [comment]
I understand. The best way would then be to have the debugger notify the listeners. But I imagine that's quite a bit more work, so probably not worth it.
Closing for now. Thanks!

**Comment by snare** [comment]
No worries. Might be worth making the timeout configurable if it's problematic?

**Comment by merlinND** [comment]
That would be a good compromise, yes!
