### ISSUE TITLE
macOS 10.13.5 Uninstall

### ISSUE THREAD

**Issue by eldardamirov** [snare/voltron#239]
How to uninstall Voltron?

**Comment by snare** [comment]
$ pip uninstall voltron

And remove it from your .lldbinit and/or .gdbinit

**Comment by eldardamirov** [comment]
Thank you for your response, but pip (brew also) are acting strange:
![2018-06-06 11 04 12](https://user-images.githubusercontent.com/29756748/41025037-84be3a10-6979-11e8-8198-d18048069711.png)

**Comment by snare** [comment]
You need to use pip from whichever Python instance it is actually installed into. If you’ve installed Python 3 from brew, the `pip` in your path is probably Python 3’s pip. Try:

$ /usr/bin/python -m pip uninstall voltron

**Comment by eldardamirov** [comment]
That worked! Thank you very much.
