### ISSUE TITLE
lldb (macos) views don't update

### ISSUE THREAD

**Issue by mellery451** [snare/voltron#244]
Thanks for this really cool toolkit. 

I'm just experimenting with lldb+macos and I can't seem to get the views to update automatically. I start my executable, voltron indicates it loaded fine. I start a view in another window and it shows me expected output for the the given debugee. However, as I step through the code, the views do not update until I send a <CR> to the window with the view (press the return key). Is this some sort of configuration that I can change or possibly something odd about my environment? 

I typically use tmux+iTerm for my shells and I've tried both with and without tmux just to eliminate that as a possible cause. I've also using the standard Terminal app in macos. All exhibit the same behavior.

lldb version is:

lldb-1000.11.37.1
  Swift-4.2

and system python is 2.7.10.

I DO have homebrew installed (including its python versions), but I've tried to be careful not to load homebrew stuff from lldb/voltron.

any advice appreciated.

**Comment by snare** [comment]
Hey, glad you like it :) this is not expected behavior - it registers a prompt hook to update the views each time the debugger stops. I haven’t had time to work on Voltron in a long time, but I’ll try to repro.

**Comment by snare** [comment]
Can't repro with my (newer) LLDB. I'll try to repro with the same version of LLDB.

**Comment by snare** [comment]
Also, when you've loaded voltron and started stepping through, what does `target stop-hook list` show you in LLDB?

**Comment by mellery451** [comment]
```
(lldb) target stop-hook list  
Hook: 1 
  State: enabled  
  Commands:  
    voltron stopped        
```
do you run a newer `lldb` by building from source, homebrew, or something else?

**Comment by mellery451** [comment]
ah...`voltron stopped` at the prompt updates things..so seems like Hook 1 is not actually triggering perhaps ?

**Comment by snare** [comment]
Huh weird.

**Comment by mellery451** [comment]
even stranger...once I manually invoke `voltron stopped` a few times (not sure what the pattern is), seems like the hook starts working after that (?). I'm working with a very simple `main()` only executable but I can't imagine that makes a difference.

**Comment by snare** [comment]
It really shouldn't. I tested with `inferior.c` from the voltron repo.

**Comment by mellery451** [comment]
I went ahead and turned on logging and started debugging:

https://gist.github.com/mellery451/2885bc7150daabe3a3021fd930f2f479
https://gist.github.com/mellery451/05196bd1a5b6020ba7d67f8fa6e557ff

What's interesting...and I suspect this was always the case...if I step about 5-10 times and then pause momentarily, the views will then start updating. So I'm confused. I guess the hook is indeed triggering, but maybe there is a timeout happening early on that eventually resolves itself (?). In any event, I hope the logs can shed some light.

**Comment by mellery451** [comment]
I'm going to close this issue b/c voltron is working perfectly for my real application. I had initially been using a very simple "hello world" application to test my voltron workflow and maybe there is just a weird timing/startup issue with that simple app. I'm happy with the way voltron works with my real-world app, so no point keeping this open. thanks.
