### ISSUE TITLE
aarch64 debugging issue

### ISSUE THREAD

**Issue by theguly** [snare/voltron#246]
testing hardware: pine64
uname -a: Linux pine64 3.10.105-bsp-1.2-ayufan-140 #1 SMP PREEMPT Tue Oct 30 14:21:35 UTC 2018 aarch64 GNU/Linux
file myexec: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), statically linked, for GNU/Linux 3.7.0, stripped

hi there, trying to debug with such environment, both lldb3.8 and gdb, i have issue like
Exception getting targets from debugger: KeyError('aarch64',)
or "aarch64 not supported"
or "Failed to get targets"

given that i used voltron+gdb and voltron+lldb on x86/amd64 linux and osx before, how can i check if i'm doing something wrong here with aarch64?

**Comment by theguly** [comment]
to complete with exact  messages, using /bin/ps from base system:

- view stack: Exception getting memory from debugger: Exception('Unsupported architecture: aarch64',)
- view reg: Architecture 'aarch64' not supported
- view disassembly: Unhandled exception <type 'exceptions.Exception'> disassembling: Unsupported architecture: aarch64

**Comment by landrufang** [comment]
hi , i get same issue , can you tell me how do you fix this . thanks

**Comment by theguly** [comment]
i think i have closed the ticket to clean my dashboard on github, not because i have found a fix - i had posted a note otherwise.
i believe my use-case was not supported - and this project looks unmaintained, i don't give many chances to a fix i'm sorry.
