### ISSUE TITLE
cannot start voltron because of import error in werkzeug

### ISSUE THREAD

**Issue by as32ofuk** [snare/voltron#271]
After installing voltron, when I start gdb it gives me this error
```An error occurred while loading Voltron:

Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/voltron/entry.py", line 57, in <module>
    import voltron
  File "/root/.local/lib/python3.6/site-packages/voltron/__init__.py", line 6, in <module>
    from .main import main
---Type <return> to continue, or q <return> to quit---
  File "/root/.local/lib/python3.6/site-packages/voltron/main.py", line 9, in <module>
    from .view import *
  File "/root/.local/lib/python3.6/site-packages/voltron/view.py", line 25, in <module>
    from .core import Client
  File "/root/.local/lib/python3.6/site-packages/voltron/core.py", line 18, in <module>
    from werkzeug.wsgi import DispatcherMiddleware, SharedDataMiddleware
ImportError: cannot import name 'DispatcherMiddleware'

Please ensure Voltron is installed correctly per the documentation: https://github.com/snare/voltron/wiki/Installation
```

I tried this on my laptop running debian buster installing manually and with the install.sh and in a docker container running ubuntu:18.04 installed with install.sh.
They all gave me the same error.
The same error appears when running the voltron command

**Comment by as32ofuk** [comment]
after forcing werkzeug version to 0.15 it works, so the current version of werkzeug (1.0) seems to be incomatible

**Comment by dukebarman** [comment]
Have a same error at macos 10.15

**Comment by rileyrg** [comment]
installing from debian 11 same issue. 

> An error occurred while loading Voltron:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/voltron/entry.py", line 57, in <module>
>     import voltron
>   File "/usr/lib/python3/dist-packages/voltron/__init__.py", line 6, in <module>
>     from .main import main
>   File "/usr/lib/python3/dist-packages/voltron/main.py", line 9, in <module>
>     from .view import *
>   File "/usr/lib/python3/dist-packages/voltron/view.py", line 25, in <module>
>     from .core import Client
>   File "/usr/lib/python3/dist-packages/voltron/core.py", line 18, in <module>
>     from werkzeug.wsgi import DispatcherMiddleware, SharedDataMiddleware
> ImportError: cannot import name 'DispatcherMiddleware' from 'werkzeug.wsgi' (/usr/lib/python3/dist-packages/werkzeug/wsgi.py)
> 
> Please ensure Voltron is installed correctly per the documentation: https://github.com/snare/voltron/wiki/Installation
> gef➤
>
