### ISSUE TITLE
Install fails on debian bullseye

### ISSUE THREAD

**Issue by rileyrg** [snare/voltron#281]
./install.sh

```
aketlisten werden gelesen… Fertig
+ echo
+ grep '3\.'
+ sudo apt-get -y install libreadline6-dev python-dev python-setuptools python-yaml python-pip
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Hinweis: »libreadline-dev« wird an Stelle von »libreadline6-dev« gewählt.
Hinweis: »python-dev-is-python2« wird an Stelle von »python-dev« gewählt.
Paket python-pip ist nicht verfügbar, wird aber von einem anderen Paket
referenziert. Das kann heißen, dass das Paket fehlt, dass es abgelöst
wurde oder nur aus einer anderen Quelle verfügbar ist.
Doch die folgenden Pakete ersetzen es:
  python3-pip

E: Paket python-yaml kann nicht gefunden werden.
E: Für Paket »python-pip« existiert kein Installationskandidat.

```

**Comment by blueyed** [comment]
Code ref: https://github.com/snare/voltron/blob/d9fef0bb4073d434c54415d55a1b5da92cb84696/install.sh#L111-L115

Should probably fail with `PYVER=2` (via `python` being a Python 2.x, or use/try `python3` instead).

Not really a problem with voltron, but only its `install.sh` script.

**Comment by rileyrg** [comment]
> Not really a problem with voltron, but only its `install.sh` script.

Erm, yes. ;)

**Comment by rileyrg** [comment]
> > Not really a problem with voltron, but only its `install.sh` script.
> 
> Erm, yes. ;) I installed it from Debian Bullseye repos, and there are issues too (it simply fell over starting up with a backtrace) but I didn't have time to follow them up - I'll look into that later and report back if I don't get it working,

OK, I had another look and it doesn't work from Debian 11 install either.  Documented async=true issues.  Much as I'd like to use it, I don't have the time currently to mess around with python as I don't know anything about it. I did follow a PR to modify "async=True" to "asynchronous = True" in memory.py but I couldn't get any voltron views to connect despite ensuring entry.py was sourced and "voltron loaded" - I even tried an addition "voltron init"  in my gdb init but no localhost:5555 connection available. I'll shelve this for now and maybe can submit more detailed bug report at a later date. A shame.
