### ISSUE TITLE
Fix the static content installation

### ISSUE THREAD

**Issue by snare** [snare/voltron#60]
Currently got __init__.py files everywhere to make sure it gets installed, do it properly with setup.py

**Comment by snare** [comment]
Cos MANIFEST.in totally works properly

**Comment by snare** [comment]
Web templates are not installed properly in #82

**Comment by alopatindev** [comment]
The workaround
```
python2 ./setup.py develop
cp ./voltron/web/templates/index.html /usr/lib64/python2.7/site-packages/voltron/web/templates/
cp ./voltron/web/static/js/bundle.js /usr/lib64/python2.7/site-packages/voltron/web/static/js/
```
works for me, thanks

**Comment by snare** [comment]
Moved the web UI to [voltron-web](https://github.com/snare/voltron-web), and fixed the static content installation
