### ISSUE TITLE
Problem with gdbinit

### ISSUE THREAD

**Issue by defau1t** [snare/voltron#64]
Hey, me again. gdb 7.4.1-debian is giving me this error:

    Exception <type 'exceptions.ImportError'> raised while loading Voltron: No module named blessed
    /home/admin/.gdbinit:2: Error in sourced command file:
    Undefined command: "voltron".  Try "help".

I'm assuming this is from the 'import blessed' line in dbgentry.py. Any ideas? 

Sorry I'm treating this as a forum since there's no official forum for voltron. Cheers

**Comment by huawenyu** [comment]
@defau1t Although past one more years, I meet the same problem ''No module named blessed" and found that's `python version` problem.

1). The error cause by the python version:
  - Show Ubuntu 14.04 publish the gdb with `python3`-interface

```Shell
$ gdb
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.

warning: ~/.gdbinit.local: No such file or directory
Exception <class 'ImportError'> raised while loading Voltron: No module named 'blessed'
/home/wilson/.gdbinit:3834: Error in sourced command file:
Undefined command: "voltron".  Try "help".
(gdb) python-interactive
>>> import sys
>>> print sys.version
  File "<stdin>", line 1
    print sys.version
            ^
SyntaxError: Missing parentheses in call to 'print'
>>> import blessed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'blessed'
>>> print(sys.version)                                                                                                                  
3.4.3 (default, Oct 14 2015, 20:31:36) 
[GCC 4.8.4]
>>> 
(gdb) quit
```

2). So we should change the setup steps a little:
  - For gdb use python3, so we should install module by `pip3`, not `pip`
```Shell
cd <your-work-dir>
git clone https://github.com/snare/voltron.git
cd voltron
sudo pip3 install flask          <<< used by next voltron setup
sudo python3 setup.py install
sudo pip3 install blessed        <<< used by voltron/dbgentry.py
```
3) If `voltron view backtrace` have connect error, please refer the comment #97.

**Comment by defau1t** [comment]
This renewed my interest in this project. It loads properly now! Just have that connect issue but will comment in that thread. Thanks @huawenyu !

**Comment by snare** [comment]
https://github.com/snare/voltron/wiki/Voltron-on-Ubuntu-14.04-with-GDB <https://github.com/snare/voltron/wiki/Voltron-on-Ubuntu-14.04-with-GDB>

**Comment by gpakosz** [comment]
I'm facing the problem on OSX

I have Python `2.7.11` installed via `brew` but Apple's Python is `2.7.10`.
I installed gdb `7.11` also via `brew`.

When I launch `/usr/local/bin/gdb` and I `print sys.version`, I get back `2.7.10`.
Now I don't really know how to make this gdb use brew's python despite `usr/local/sbin` coming first in path:

```
(gdb) path
Executable and object file path: /usr/local/bin:/usr/local/sbin:/usr/local/opt/ruby/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/sbin:/usr/local/opt/ruby/bin
```

**Comment by snare** [comment]
Can you open a new issue please? Since GDB is linked against the system Python you're probably best just to install Voltron into the system Python.

**Comment by gpakosz** [comment]
Well I wasn't sure about opening an issue. The fact that you mentioned again GDB **is linked against the system Python** made me realize reinstalling it with `brew install gdb --with-python` rebuilds it and links it against brew's Python.

So it's all good now, and people may find that comment in the current issue.
