### ISSUE TITLE
error: Could not find suitable distribution for Requirement.parse('yaml')

### ISSUE THREAD

**Issue by draozoth** [snare/voltron#70]
Hello! I've been trying to get this set up for a while, maybe you can tell me what I am doing wrong. I get this error when using setup.py install....

error: Could not find suitable distribution for Requirement.parse('yaml')

Any Ideas?

**Comment by snare** [comment]
I'm assuming you're on Linux? I came across when I was testing on Linux the other day. I'll have a look now.

**Comment by snare** [comment]
In the mean time, you will probably need to follow the [install steps for Ubuntu](https://github.com/snare/voltron/wiki/Voltron-on-Ubuntu-14.04-with-GDB) (now linked from the wiki)

**Comment by snare** [comment]
Could you do the following for me:

In your shell:

	$ python -c "import sys;print sys.version"

In GDB:

	gdb$ python import sys;print sys.version

And paste the results?

**Comment by draozoth** [comment]
Sure can, thanks.
$ python -c "import sys;print sys.version":
     2.7.3 (default, Mar 13 2014, 11:03:55) 
     [GCC 4.7.2]

gdb$ python import sys;print sys.version
     2.7.3 (default, Mar 13 2014, 11:26:58) 
     [GCC 4.7.2]

I have both python 3 and 2.7 installed, however 2.7 is the default.  I also tried with the "python3" command as opposed to just the "python" command.  Hope that helps.

**Comment by snare** [comment]
Ok, so GDB is linked against Python 2. Interesting that the timestamps differ, but that could just be the library version vs the executable itself.

You can ignore the Ubuntu instructions then, since that’s not the problem.

**Comment by draozoth** [comment]
It's acting like there is no package called yaml to install... I think if I could get that figured out everything would be good.  When I load up gdb it says Voltron Loaded.  It just gives an error now when trying to link up to voltron with my panes.

et0x@mnstr:~$ voltron view register -v
Traceback (most recent call last):
  File "/usr/local/bin/voltron", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: yaml

**Comment by snare** [comment]
Try:

	$ apt-get install python-yaml

Or:

	$ pip install pyyaml

I installed pyyaml on Ubuntu using APT, but there seems to be an issue with setuptools where it still doesn’t recognise the package once it’s installed, so the `voltron` command errors.

**Comment by draozoth** [comment]
I had tried both of those before this ... both packages are installed and still get the errors!  At a loss :)

**Comment by snare** [comment]
OK I think I found it. Stupid mistake. Please download the latest [scruffy](https://github.com/snare/scruffy) and install it manually first. That's what actually has the yaml requirement. If that works, remove "scruffy" as a dependency from the Voltron setup.py and try installing it again. I'll push a fix to the repo if that works.

**Comment by snare** [comment]
Actually you don't need to remove the scruffy dependency from the setup.py. Just install the latest scruffy first. That should fix it.

**Comment by draozoth** [comment]
Great that fixed the problem -- however, I have a different one now.Sorry for this, I greatly appreciate the time you've put towards getting these resolved.  Here is the error I received.

(gdb) b * 0x08048420
Breakpoint 1 at 0x8048420
(gdb) run
Starting program: /home/et0x/Downloads/test
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/voltron-0.1-py2.7.egg/voltron/core.py", line 202, in run
    rfds, _, _ = select.select([serv, self.exit_pipe] + self.clients, [], [])
error: (4, 'Interrupted system call')

I seem to get this with every binary I load.

**Comment by snare** [comment]
Ah this one is something someone else has run into as well. No fix yet, but I haven’t been able to reproduce it yet. What version of debian are you running? I’ll spin up a VM and see if I can reproduce it.

And no worries, I really want Voltron to work properly on Linux but I’ve been really slack testing it.

**Comment by snare** [comment]
See the discussion in #65 for a debug version to run

**Comment by draozoth** [comment]
Debian 7, Kali Linux!  Thanks for the quick responses.

**Comment by draozoth** [comment]
Kali 1.0.9, thanks for the quick resonses !

**Comment by snare** [comment]
Hey, if you're still having this problem can you try the latest commit? I've added a bunch of fixes for Python 3 and Linux stuff, just curious to see if this is still happening on Kali. I don't have it handy and I'm on cellular at the moment so I can't download an ISO.
