### ISSUE TITLE
When backtrace view is enabled with lldb, pressing enter to repeat last command triggers backtrace.

### ISSUE THREAD

**Issue by mcourteaux** [snare/voltron#74]
Instead of repeating the last command (eg: ni), the backtrace does output in the debugger (lldb) when hitting Enter.

**Comment by snare** [comment]
Yeah, same as #59. I started to add a proper backtrace view (at the moment it just issues a 'bt' command and prints out the output) but it's not done yet.

Thanks!

**Comment by snare** [comment]
This is basically because any use of the `command` API method goes via the `SBCommandInterpreter` instance that's shared with the CLI. I've been meaning to see if I can execute commands without them being added to the history, but I haven't looked into it yet. Will suss it out.
