### ISSUE TITLE
Voltron should be easier to install

### ISSUE THREAD

**Issue by Stolas** [snare/voltron#83]
Getting exceptions like: 'Exception <class 'ImportError'> raised while loading Voltron: No module named 'blessed'
Should not occur, as the install.py should take care of this.

**Comment by alex-bender** [comment]
Same error for me

**Comment by Stolas** [comment]
Good way to debug the issue (I did do this), but still it stands that it should be in the install script like @snare stated in #64 .

I might throw some time against this issue to make Voltron auto-install this.

**Comment by snare** [comment]
Blessed is in the setup.py deps, not sure why this would be happening.

Which platform?

**Comment by Stolas** [comment]
I am using Ubuntu, let me retry tonight.

**Comment by snare** [comment]
Make sure you’re using the right Python, per https://github.com/snare/voltron/wiki/Voltron-on-Ubuntu-14.04-with-GDB <https://github.com/snare/voltron/wiki/Voltron-on-Ubuntu-14.04-with-GDB>

**Comment by Stolas** [comment]
Epic, I just missed some docs. This is exactly what I missed in Unix!

**Comment by snare** [comment]
Cool. I should probably put that shit in the readme eh. Common problem.

**Comment by Stolas** [comment]
Wouldn't it be easier if either of us would make a deb file?
This way, people like me, can install it without RTFM.
