### ISSUE TITLE
Connecting to Voltron from another computer

### ISSUE THREAD

**Issue by tmr232** [snare/voltron#88]
While the server can listen on `TCP`, it seems that the client is hard-coded to use a `UNIX_SOCKET`. Is there an existing client that can connect to Voltron from a remote host?

**Comment by snare** [comment]
Hey, sorry it took so long to get to this. I'm rewriting the core ATM and will fix this as part of it. Currently the included views are hardcoded to use the domain socket.

**Comment by snare** [comment]
Should be able to do this with 37502daec1fce43e31c22f02b3af06ea299d38ca. By default the server listens on `localhost:5555`.

Add to the voltron server's config (the one running in the debugger):
```
{
    "server": {
        "listen": {
            "domain":   "~/.voltron/sock",
            "tcp":      ["0.0.0.0", 5555]
        }
    }
}
```

And the client (the one running the views):
```
{
    "view": {
        "api_url": "http://10.0.0.1:5555/api/request"
    }
}
```
with the server's address
