### ISSUE TITLE
SSE Registers are displayed as N/A when using LLDB

### ISSUE THREAD

**Issue by mbebenita** [snare/voltron#94]
I'm using lldb-340.4.70. When running 'voltron view register -sse, SSE registers are displayed as `n/a`. I tracked the bug down to line:

https://github.com/snare/voltron/blob/master/voltron/plugins/debugger/dbg_lldb.py#L201

SBValues for XMM registers don't have a valid value. In order to work around it, I have to iterate over all its children instead.

```python
if reg.value != None:
  try:
      val = reg.GetValueAsUnsigned()
  except:
      reg = None
elif reg.num_children > 0:
  children = []
  for i in range (reg.GetNumChildren()):
      children.append(reg.GetChildAtIndex(i, lldb.eNoDynamicValues, True).value)
  val = ", ".join(children)
```

**Comment by snare** [comment]
Fixed in 56d06fb59b3f85aea8b6038a0980e2712bcf8a6c (I think)
